name: Dev to main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test -- --ci

      - name: Set up Git credentials
        run: |
          git config --global user.name "kaciefrei"
          git config --global user.email "kaci.bouaouli@efrei.net"

      - name: Fetch remote branches
        run: |
          git fetch origin

      - name: Checkout main branch
        run: |
          git checkout main || git checkout -b main
          git pull origin main

      - name: Merge dev into main with conflict resolution
        run: |
          git merge origin/dev --allow-unrelated-histories || git merge --abort  # if merge fails
          git add backend/app.js  # add the resolved file (if any conflict)
          git commit -m "Resolved merge conflict"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
